"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { useLocale } from "@/lib/locale-context"
import { toast } from "sonner"
import { ArrowLeft, Loader2 } from "lucide-react"
import Link from "next/link"
import { ImageUpload } from "@/components/ui/image-upload"

export default function AddCategoryPage() {
  const { t } = useLocale()
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [formData, setFormData] = useState({
    name: "",
    slug: "",
    description: "",
    image: ""
  })

  const generateSlug = (name: string) => {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
  }

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value
    setFormData({
      ...formData,
      name,
      slug: generateSlug(name)
    })
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.name || !formData.slug) {
      toast.error(t.admin.fillRequired)
      return
    }

    try {
      setLoading(true)
      const response = await fetch("/api/categories", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      })

      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.error || t.admin.errorCreate)
      }

      toast.success(t.admin.successCreate)
      router.push("/admin/categories")
    } catch (error: unknown) {
      console.error("Error creating category:", error)
      toast.error(error instanceof Error ? error.message : t.admin.errorCreate)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-4 sm:space-y-6 pb-6 sm:pb-8">
      <div className="flex items-center gap-3 sm:gap-4">
        <Link href="/admin/categories">
          <Button variant="ghost" size="icon" className="h-8 w-8 sm:h-10 sm:w-10">
            <ArrowLeft className="w-4 h-4 sm:w-5 sm:h-5" />
          </Button>
        </Link>
        <div>
          <h1 className="heading-responsive-h2 text-slate-900 dark:text-white">{t.admin.addCategory}</h1>
          <p className="text-responsive-sm text-muted-foreground">{t.admin.createNewCategory}</p>
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        <Card className="border-0 shadow-sm max-w-3xl">
          <CardContent className="p-4 sm:p-6 space-y-4 sm:space-y-6">
            <div className="space-y-2">
              <Label htmlFor="title" className="text-responsive-sm font-medium text-slate-700 dark:text-slate-300">
                {t.admin.categoryName} <span className="text-red-500">*</span>
              </Label>
              <Input 
                id="title" 
                placeholder={t.admin.enterCategoryName}
                className="h-10 sm:h-11"
                value={formData.name}
                onChange={handleNameChange}
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="slug" className="text-responsive-sm font-medium text-slate-700 dark:text-slate-300">
                {t.admin.categorySlug} <span className="text-red-500">*</span>
              </Label>
              <Input 
                id="slug" 
                placeholder="category-slug" 
                className="h-10 sm:h-11"
                value={formData.slug}
                onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                required
              />
              <p className="text-xs text-muted-foreground">{t.admin.autoGeneratedSlug}</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="description" className="text-responsive-sm font-medium text-slate-700 dark:text-slate-300">
                {t.admin.categoryDescription}
              </Label>
              <Textarea
                id="description"
                placeholder={t.admin.writeCategoryDescription}
                rows={4}
                className="resize-none"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label className="text-responsive-sm font-medium text-slate-700 dark:text-slate-300">
                {t.admin.categoryImage}
              </Label>
              <ImageUpload
                value={formData.image}
                onChange={(url) => setFormData({ ...formData, image: url })}
                disabled={loading}
              />
            </div>

            <div className="pt-4 flex flex-col sm:flex-row gap-3">
              <Button 
                type="submit"
                className="bg-[#F97316] hover:bg-[#EA580C] text-white btn-responsive" 
                disabled={loading}
              >
                {loading && <Loader2 className="icon-responsive mr-2 animate-spin" />}
                {t.common.save} {t.common.category}
              </Button>
              <Link href="/admin/categories" className="w-full sm:w-auto">
                <Button type="button" variant="outline" className="btn-responsive w-full">
                  {t.common.cancel}
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </form>
    </div>
  )
}


